# Path: config/stock_inference.yaml

# Inferencing configuration
run_name: aapl_lstm

# Stock configuration
dataset: StockDataset
name: AAPL
currency: USD
features: Close
start: "1990-01-01" # Inference start date
end: "2022-01-01" # Inference end date
interval: 1d

# Model & Strategy configuration
model: LSTMModel
strategy: SignalStrategy

# Hyperparameters
input_size: 1
hidden_size: 50
num_layers: 1
output_size: 1
window_size: 365
batch_size: 16
epochs: 50
learning_rate: 0.001
dropout: 0.2
bidirectional: False

# Save configuration
save_model: True
save_data: False
model_save_path: "krtrader/ckpt/lstm.pth"
data_save_path: "krtrader/data/cache/stock.csv"

# Others
trade_num: 100
init_asset: 1000000