# Trade-only configurations

name: ["AAPL", "BA", "DIS", "GOOG", "GE", "NKE"]
model: None
strategy: None
currency: USD
features: Close
start: "2010-01-01"
end: "2020-01-01"
interval: 1d

trade_num: 100
init_asset: 1000000
log_stamp: simulated_trade
